# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=32, unique=True)),
                ('member_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
