# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-23 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='The text of the message', max_length=128)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this message was sent')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='The username of this Member', max_length=128, unique=True)),
                ('reply_channel_name', models.CharField(help_text='The Django Channels identifier that can be used to send messages back to the user', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this Room', max_length=32, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='room',
            field=models.ForeignKey(help_text='The Room this Memebr belongs too.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.Room'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='room',
            field=models.ForeignKey(help_text='The Room this ChatMessage belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.Room'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(help_text='The Member that sent this message.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.Member'),
        ),
    ]
