#!/usr/bin/env bash

function help() {
    echo "Runs application management commands."
    echo "Usage:"
    echo "$ ./app [ build | start | stop | restart ]"
}

function build() {
    docker-compose build --no-cache
    run web python manage.py migrate
}

function start() {
    docker-compose up
}

function stop() {
    docker-compose stop
}

function run() {
    echo "${@:2}"
    docker-compose run --rm $1 "${@:2}"
}


if [[ $# < 1 ]]; then
    help

elif [[ $1 == "build" ]]; then
    stop
    build

elif [[ $1 == "start" ]]; then
    start

elif [[ $1 == "stop" ]]; then
    stop

elif [[ $1 == "restart" ]]; then
    stop
    start

elif [[ $1 == "run" ]]; then
    run ${@:2}


elif [[ $1 == "makemigrations" ]]; then
    run web python manage.py makemigrations


elif [[ $1 == "migrate" ]]; then
    run web python manage.py migrate

else
    help

fi
