# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"

  config.vm.synced_folder "./", "/vagrant"

  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update -y

    # Install pip for Python 3.5
    if ! command -v pip3; then
       sudo apt-get install python3-pip -y
    fi

    pip3 install virtualenv --upgrade

    cd /vagrant/
    virtualenv venv

    source venv/bin/activate

    pip install -r requirements.txt

  SHELL
end
